project/models.py
# project/models.py

from project import db, bcrypt
from sqlalchemy.orm import relationship
from sqlalchemy import func, ForeignKey, event
from sqlalchemy.engine import Engine
from sqlite3 import Connection as SQLite3Connection


import sqlite3

from sqlalchemy.engine import Engine
from sqlalchemy import event

@event.listens_for(Engine, "connect")
def set_sqlite_pragma(dbapi_connection, connection_record):
    if type(dbapi_connection) is sqlite3.Connection:  # play well with other DB backends
       cursor = dbapi_connection.cursor()
       cursor.execute("PRAGMA foreign_keys=ON")
       cursor.close()

class User(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=True)
    password = db.Column(db.String, nullable=False)
    detailRel = db.relationship('Details', backref='user', lazy='joined', uselist=False)

    def __init__(self, name, password):
        self.name = name
        self.password = bcrypt.generate_password_hash(password)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<name {}'.format(self.name)

class Details(db.Model):
    __tablename__ = "details"

    id = db.Column(db.Integer, primary_key = True)

    confirmed = db.Column(db.Boolean, nullable = True)
    confirmed_on = db.Column(db.DateTime, nullable = True)
    registered_on = db.Column(db.DateTime, nullable = False)
    email = db.Column(db.String, unique = False, nullable = False) # in production set to unique=True
    locale = db.Column(db.String, nullable = True)
    gender = db.Column(db.Boolean, nullable = True)
    age = db.Column(db.Integer, nullable = True)

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __init__(self, email, gender, age, locale, user_id, user = None, confirmed_on = None, confirmed = False):
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on
        self.registered_on = func.now()
        self.email = email
        self.gender = gender
        self.age = age
        self.locale = locale
        self.user_id = user_id
        self.user = user

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_mail import Mail
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from flask_jsglue import JSGlue

from sqlalchemy import *
from sqlalchemy import event
from sqlalchemy.orm import *
from sqlalchemy.engine import Engine
from sqlalchemy.ext.declarative import declarative_base
################
#### config ####
################

app = Flask(__name__)

app.config.from_object(os.environ['APP_SETTINGS'])
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)
jsglue = JSGlue(app)
mail = Mail(app)
session = Session(app)



####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)


####################
#### flask-login ####
####################

from project.models import User

login_manager.login_view = "user.authorize"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/main/views.py
# project/main/views.py

#################
#### imports ####
#################

from flask import render_template, Blueprint
from flask_login import login_required
from project.history.historyParser import*
# from project.history import*
################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)

################
#### routes ####
################

@main_blueprint.route('/')
@main_blueprint.route('/index')
@login_required
def home():
    return render_template('main/index.html', data = parse())

project/user/views.py
# project/user/views.py

#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, current_user
from project.models import User, Details
from project import app, db, bcrypt
# from project.email import send_email
from datetime import datetime
from tempfile import mkdtemp
from sqlalchemy import func

from .helpers import*
import distutils
import requests

from project.token import generate_confirmation_token, confirm_token
from project.email import send_email

################
#### config ####
################
if app.config["DEBUG"]:
    @app.after_request
    def after_request(response):
        response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
        response.headers["Expires"] = 0
        response.headers["Pragma"] = "no-cache"
        return response

    # configure session to use filesystem (instead of signed cookies)
    app.config["SESSION_FILE_DIR"] = mkdtemp()
    app.config["SESSION_PERMANENT"] = False
    app.config["SESSION_TYPE"] = "filesystem"


user_blueprint = Blueprint('user', __name__)

################
#### routes ####
################

# @app.before_request
# def make_session_permanent():
#     session.permanent = True

@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')

    user = Details.query.filter_by(user_id = current_user.id).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_on = func.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('main.home'))

@user_blueprint.route('/authorize', methods=['GET', 'POST'])
def authorize():
    form = request.form
    username = form.get('username')
    usernameReg = form.get('usernameReg')

    if form.get("signInButton") :
        """Log user in."""
        if current_user.is_authenticated:
            return redirect(url_for('main.home'))
        # if user reached route via POST (as by submitting a form via POST)
        if request.method == "POST":

            # ensure username or pwd was submitted
            if not username or not form.get("pass"):
                flash('must provide username or pass', 'danger')
                return apology("must provide username or pass")

            user = User.query.filter_by(name = username).first()

            remember_me = False
            if form.get("check"): remember_me = True

            # ensure username exists and password is correct
            if user and bcrypt.check_password_hash(user.password, form.get("pass")):
                login_user(user, remember=remember_me)
                flash('Welcome.', 'success')
                return redirect(url_for('main.home'))
            else:
                flash('Invalid email and/or password.', 'danger')
                return render_template('user/authorize.html', form=form)

    else:
        """Register user."""
        # if user reached route via POST (as by submitting a form via POST)
        if request.method == "POST":

            # ensure username was submitted
            if not usernameReg:
                return apology("Missing username!")
            # ensure password was submitted
            elif not form.get("password"):
                return apology("Missing password!")
            # ensure confirm_password was submitted
            elif not form.get("confirm_password"):
                return apology("Missing confirm password!")
            elif not form.get("password")==form.get("confirm_password"):
                return apology("Passwords do not match!")
            elif not form.get("email"):
                return apology("Missing email!")

            try:
                countryJson = requests.get('https://api.ipdata.co/').json()
                countryCode = countryJson['country_code']
            except:
                countryCode = None

            user = User.query.filter_by(name = usernameReg).first()
            if user is None:
                gender = None;
                if not form.get("gender") == "null":
                    gender =  bool(distutils.util.strtobool(form.get("gender")))

                user = User(password = form.get("password"), name = usernameReg)
                db.session.add(user)
                db.session.commit()

                email = form.get("email")
                details = Details(email = email, gender = gender, age = int(form.get("age")), locale = countryCode, user_id = user.id, confirmed = False, user = user)
                db.session.add(details)
                db.session.commit()

            else:
                return apology("Something wrong...Maybe the username was already registered.")

            token = generate_confirmation_token(email)

            confirm_url = url_for('user.confirm_email', token=token, _external=True)
            html = render_template('user/activate.html', confirm_url = confirm_url)
            subject = "Please confirm your email"
            send_email(email, subject, html)
            login_user(user)

            flash('You registered and are now logged in. Welcome!', 'success')
            return redirect(url_for('main.home'))

            # return redirect(url_for("unconfirmed"))

    return render_template("user/authorize.html", form=form)

@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('user.authorize'))

project/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Chartex : {% block title %}{% endblock %}</title>
    <meta charset="utf-8"/>
    <meta content="initial-scale=1, width=device-width" name="viewport"/>
    <!-- styles -->
    <link href="http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>

    <link href="{{url_for('static', filename='load.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body >
    <h1 id = "load">
      <span class="let1">l</span>
      <span class="let2">o</span>
      <span class="let3">a</span>
      <span class="let4">d</span>
      <span class="let5">i</span>
      <span class="let6">n</span>
      <span class="let7">g</span>
    </h1>

    {% include "navi.html" %}

    <div class="container">

      <br>
      <div  style= "margin-top:35px">
      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert" >&times;</a>
           {{message}}
          </div>
          {% endfor %}
        </div>
      </div>
      {% endif %}
      {% endwith %}
      </div>

      <!-- child template -->
      {% block content %}{% endblock %}

      <br>

      <!-- errors -->
      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}</p>
      {% endif %}

    </div>

    <!-- scripts -->
    <script src='https://code.jquery.com/jquery-3.1.1.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>

    <script src='static/dist/commonbundle.js' type='text/javascript'></script>
    <!--<script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>-->
    {% block js %}{% endblock %}
  </body>
  <script>
    document.getElementById("load").className = "paused";
    document.body.style.backgroundColor = "#FF9966";
</script>
</html>

project/templates/apologyLayout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta content="initial-scale=1, width=device-width" name="viewport"/>

        <title>Chartex : {% block title %}{% endblock %}</title>
    </head>
    <body>
            <main>
                {% block main %}{% endblock %}
            </main>
    </body>
</html>

project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta -->
        <meta charset="utf-8"/>
        <meta content="initial-scale=1, width=device-width" name="viewport"/>

        <!-- documentation at http://getbootstrap.com/, alternative themes at https://www.bootstrapcdn.com/bootswatch/ -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>

        <!--<link href="{{ url_for('static', filename='styles.css') }}" rel="stylesheet"/>-->
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="static/dist/load.css"  ">

        <title>Chartex : {% block title %}{% endblock %}</title>
        <style>.paused{display: none;} </style>
    </head>

    <body>
         <h1>
            <span class="let1">l</span>
            <span class="let2">o</span>
            <span class="let3">a</span>
            <span class="let4">d</span>
            <span class="let5">i</span>
            <span class="let6">n</span>
            <span class="let7">g</span>
          </h1>
        <div class="container">
            <main>
                {% block main %}{% endblock %}
            </main>
        </div>
        <script src='static/dist/commonbundle.js' type='text/javascript'></script>
        <script>
            window.onload = function() {
            var spanTags =  document.getElementsByTagName("span");
            var spanlen = spanTags.length;
            var i = 0;
            for (;i < spanlen; i++)spanTags[i].className = "paused";
        };
        </script>
    </body>
</html>

project/templates/navi.html
<head>
  <link rel="stylesheet" href="static/style.css">
</head>
<!--move to head in layout _base-->
<nav class="navbar-fixed-top" role="navigation">
<header>
  <div class="container">

    <div class="logo-box">
    <img src="static/images/chartx.qNCDV.png" >
    </div>
    <nav>
    <ul>
    {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('main.home') }}">home</a></li>
    {% endif %}
    {% if current_user.is_authenticated %}
         <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
    {% else %}
        <li><a href="{{ url_for('user.authorize') }}">Authorize</a></li>
    {% endif %}
        <li><a href="">about</a></li>
        <li><a href="">contact</a></li>
    </ul>
    </nav>
  </div>
</header>
</nav>